Releases in absentia
thecoshman/http pull request #153
Opened 2023-03-21 12:06 UTC by nabijaczleweli

[`v1.12.6`](https://github.com/thecoshman/http/releases/tag/v1.12.6)

2023-08-26 10:01 UTC, thecoshman requested changes

2023-08-26 10:01 UTC, thecoshman commented on appveyor.yml
> +  - bash -lc "pacman --noconfirm -Syyu"
Isn't this the same line twice? Mistake, or strange behavior with what's being run?

2023-08-26 10:01 UTC, thecoshman commented on http.md
> +  --proxy-redir [HEADER-NAME:CIDR]
Mind just explaining for my sake what this is actually doing... it's about handling automatic redirects and having certain headers automatically renamed under certain conditions?

2023-08-26 10:01 UTC, thecoshman commented on src/ops/mod.rs
> +        for (network, header) in &self.proxy_redirs {
Why not pull this 1`for` out to it's own function, that can either return the eventual `Some(HttpHandler::slashise(s.to_string()));` or if gets through everything returns the initial URL. That way `new_url` doesn't need to be `mut`... it can also do with a better name than just `new_url`

2023-08-26 10:14 UTC, nabijaczleweli commented on appveyor.yml
> +  - bash -lc "pacman --noconfirm -Syyu"
Double upgrade required for some reason, yes.

2023-08-26 10:26 UTC, nabijaczleweli commented on http.md
> +  --proxy-redir [HEADER-NAME:CIDR]
It's for when you have a
```
location / {
    proxy_pass http://127.0.0.1:8211/some-different-URI-root$request_uri;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Original-URL https://$server_name$request_uri;
}
```

We already handled X-Forwarded-For, but it's just for logging:
```
[2023-08-26 12:07:10] 127.0.0.1:49258 for 95.181.232.30, 188.114.111.21 was served file /mnt/filling/store/nabijaczleweli/debian.nabijaczleweli.xyz/dists/bookworm/InRelease as text/plain
```

In this example let's say we have `http /mnt/filling/store/nabijaczleweli/debian.nabijaczleweli.xyz/dists` and
```
location ~ /dists(.*) {
    proxy_pass http://127.0.0.1:8000$1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Original-URL https://$server_name$request_uri;
}
```

If, in this example, someone requests `https://debian.nabijaczleweli.xyz/dists/bookworm` we need to redirect them to `https://debian.nabijaczleweli.xyz/dists/bookworm/` and return the generated index for that URL.

Without this flag, we redirected to `/bookworm/` (which is equivalent to `https://debian.nabijaczleweli.xyz/bookworm`, and wrong).

2023-08-26 10:46 UTC, nabijaczleweli commented on src/ops/mod.rs
> +        for (network, header) in &self.proxy_redirs {
Lifted

2023-08-28 15:48 UTC, thecoshman commented on appveyor.yml
> +  - bash -lc "pacman --noconfirm -Syyu"
Ergh... a stupid thing but I guess not much we can do about it. Maybe a comment to explain that it actually is needed

2023-08-30 15:02 UTC, merged